// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByZ9ivvsd-0D2pJCUItazyohcJg95leJA',
    appId: '1:696683420655:web:1b45532f385f68da54f41a',
    messagingSenderId: '696683420655',
    projectId: 'collablearn-cf7a5',
    authDomain: 'collablearn-cf7a5.firebaseapp.com',
    storageBucket: 'collablearn-cf7a5.firebasestorage.app',
    measurementId: 'G-1F3QC1ZPDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO5zmnI4eBs0h-QvVIGvU2WTCQtZSVG48',
    appId: '1:696683420655:android:b768735b3d0e6e6854f41a',
    messagingSenderId: '696683420655',
    projectId: 'collablearn-cf7a5',
    storageBucket: 'collablearn-cf7a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzf7_PGUYyOgAj2yfCFkSWmcVztScG-mc',
    appId: '1:696683420655:ios:4617fd2ba352553a54f41a',
    messagingSenderId: '696683420655',
    projectId: 'collablearn-cf7a5',
    storageBucket: 'collablearn-cf7a5.firebasestorage.app',
    iosBundleId: 'com.example.collablearn1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzf7_PGUYyOgAj2yfCFkSWmcVztScG-mc',
    appId: '1:696683420655:ios:4617fd2ba352553a54f41a',
    messagingSenderId: '696683420655',
    projectId: 'collablearn-cf7a5',
    storageBucket: 'collablearn-cf7a5.firebasestorage.app',
    iosBundleId: 'com.example.collablearn1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByZ9ivvsd-0D2pJCUItazyohcJg95leJA',
    appId: '1:696683420655:web:106348c1c69be02454f41a',
    messagingSenderId: '696683420655',
    projectId: 'collablearn-cf7a5',
    authDomain: 'collablearn-cf7a5.firebaseapp.com',
    storageBucket: 'collablearn-cf7a5.firebasestorage.app',
    measurementId: 'G-L3X185GFMZ',
  );
}
